name: smart_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_v2: ^5.4.0
  provider: ^6.1.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  pin_code_fields: ^8.0.1
  lottie: ^3.3.1
  intl: any
  flutter_launcher_icons: ^0.14.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.14.0
  flutter_date_pickers: ^0.4.3
  flutter_datetime_picker_plus: ^2.2.0
  go_router: ^15.1.3
  shared_preferences: ^2.5.3
  firebase_dynamic_links: ^6.1.7
  supabase_flutter: ^2.9.1
  dio: ^5.4.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  riverpod: ^2.5.1
  shimmer: ^3.0.0



  flutter_localizations:
    sdk: flutter
  permission_handler: ^12.0.1
  device_preview: ^1.3.1
#  flutter_native_splash: ^2.4.7
#  google_maps_flutter: ^2.12.3
#  geolocator: ^14.0.2
#  geocoding: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #  uni_links:
  #    path: packages/uni_links
  #  uni_links: ^0.5.1


  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"




#flutter_native_splash:
#  android: true
#  ios: true
#  background_image: assets/images/splash_bg.png
#  android_12:
#    background_image: assets/images/splash_bg.png





flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/lottie/

